# Generated by Django 4.1.7 on 2023-07-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_limit", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="userdetails",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
