# Generated by Django 4.1.7 on 2023-04-09 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_reserveconsulation_results_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservationfacilities",
            name="facility",
        ),
        migrations.AddField(
            model_name="reservationfacilities",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.facilites",
            ),
        ),
    ]
