# Generated by Django 4.1.7 on 2023-07-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_reservationsettings_userdetails_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
