# Generated by Django 4.1.7 on 2023-04-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_remove_reservationfacilities_facility_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservationfacilities",
            name="facility",
        ),
        migrations.AddField(
            model_name="reservationfacilities",
            name="facility",
            field=models.ManyToManyField(to="reservation.facilites"),
        ),
    ]
