# Generated by Django 4.1.7 on 2023-07-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_userdetails_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationsettings",
            name="reservation_current",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
