# Generated by Django 4.1.7 on 2023-08-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_alter_prescription_result_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctordetails",
            options={"verbose_name_plural": "Doctor Details"},
        ),
        migrations.AlterModelOptions(
            name="facilites",
            options={"verbose_name_plural": "Facilities"},
        ),
        migrations.AlterModelOptions(
            name="messages",
            options={"verbose_name_plural": "Messages"},
        ),
        migrations.AlterModelOptions(
            name="reservationfacilities",
            options={"verbose_name_plural": "Reserved Services"},
        ),
        migrations.AlterModelOptions(
            name="reservationsettings",
            options={"verbose_name_plural": "Reservation Settings"},
        ),
        migrations.AlterModelOptions(
            name="reserveconsulation",
            options={"verbose_name_plural": "Reserved Consultation"},
        ),
        migrations.AlterModelOptions(
            name="results",
            options={"verbose_name_plural": "Results"},
        ),
        migrations.AlterModelOptions(
            name="services",
            options={"verbose_name_plural": "Services"},
        ),
        migrations.AlterModelOptions(
            name="speciality",
            options={"verbose_name_plural": "Specialities"},
        ),
        migrations.AlterModelOptions(
            name="userdetails",
            options={"verbose_name_plural": "User Details"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_doctor",
            field=models.BooleanField(default=False, verbose_name="Doctor"),
        ),
    ]
