# Generated by Django 4.1.7 on 2023-07-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_reservationsettings_reservation_current"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctordetails",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="doctordetails",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="doctordetails",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="doctordetails",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="doctordetails",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="doctordetails",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="doctordetails",
            name="placebirth",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
