# Generated by Django 4.1.7 on 2023-08-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0004_alter_doctordetails_options_alter_facilites_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
