# Generated by Django 4.1.7 on 2023-07-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0005_alter_doctordetails_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="token",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
    ]
