# Generated by Django 4.1.7 on 2023-08-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0005_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="is_first_login",
            field=models.BooleanField(default=True),
        ),
    ]
