# Generated by Django 4.1.7 on 2023-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0006_userdetails_is_first_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctordetails",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
    ]
