# Generated by Django 4.1.7 on 2023-04-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0007_reserveconsulation_date_created_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="bdate",
            field=models.DateTimeField(),
        ),
    ]
