# Generated by Django 4.1.7 on 2023-07-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0008_perscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserveconsulation",
            name="timeslot",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=1, null=True
            ),
        ),
    ]
