# Generated by Django 4.1.7 on 2023-04-09 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0008_alter_doctordetails_bdate_alter_userdetails_bdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctordetails",
            name="rndid",
            field=models.CharField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reserveconsulation",
            name="doctors_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdetails",
            name="rndid",
            field=models.CharField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                max_length=100,
                null=True,
            ),
        ),
    ]
