# Generated by Django 4.1.7 on 2023-04-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0008_alter_userdetails_bdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctordetails",
            name="bdate",
            field=models.DateTimeField(),
        ),
    ]
