# Generated by Django 4.1.7 on 2023-04-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0009_doctordetails_rndid_reserveconsulation_doctors_id_and_more",
        ),
        ("reservation", "0011_alter_doctordetails_bdate_alter_userdetails_bdate"),
    ]

    operations = []
