# Generated by Django 4.1.7 on 2023-07-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0011_alter_reserveconsulation_timeslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationfacilities",
            name="patient",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
