# Generated by Django 4.1.7 on 2023-04-09 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0012_merge_20230409_1947"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctordetails",
            name="speciality",
        ),
        migrations.AlterField(
            model_name="reserveconsulation",
            name="doctors_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="doctordetails",
            name="speciality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.speciality",
            ),
        ),
    ]
