# Generated by Django 4.1.7 on 2023-07-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0013_reservationfacilities_reservation_current_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservationfacilities",
            name="reservation_current",
        ),
        migrations.RemoveField(
            model_name="reservationfacilities",
            name="reservation_limit",
        ),
        migrations.AddField(
            model_name="facilites",
            name="reservation_current",
            field=models.IntegerField(default="1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facilites",
            name="reservation_limit",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
