# Generated by Django 4.1.7 on 2023-07-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0014_remove_reservationfacilities_reservation_current_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="reservation_current",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="services",
            name="reservation_limit",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
