# Generated by Django 4.1.7 on 2023-04-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0014_messages_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctordetails",
            name="bdate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="bdate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
