# Generated by Django 4.1.7 on 2023-04-09 19:27

from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0015_alter_doctordetails_bdate_alter_userdetails_bdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="reference_number",
            field=models.CharField(
                blank=True,
                default=reservation.models.create_rand_id,
                editable=False,
                max_length=13,
                null=True,
            ),
        ),
    ]
