# Generated by Django 4.1.7 on 2023-07-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0016_alter_reservationfacilities_timeslot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationfacilities",
            name="timeslot",
            field=models.CharField(
                choices=[("1", "6:00AM - 12:00NN"), ("2", "1:00PM - 6:00PM")],
                default=1,
                max_length=1,
            ),
        ),
    ]
