# Generated by Django 4.1.7 on 2023-04-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0017_alter_facilites_facility_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserveconsulation",
            name="patient",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="billing",
            name="total_payment",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
