# Generated by Django 4.1.7 on 2023-04-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0019_alter_reserveconsulation_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationfacilities",
            name="schedule",
            field=models.DateTimeField(editable=False),
        ),
    ]
