# Generated by Django 4.1.7 on 2023-04-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0020_alter_reservationfacilities_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationfacilities",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reserveconsulation",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
