# Generated by Django 4.1.7 on 2023-04-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0021_reservationfacilities_is_done_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationfacilities",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reserveconsulation",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
