# Generated by Django 4.1.7 on 2023-04-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0022_reservationfacilities_is_cancelled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationfacilities",
            name="schedule",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="reserveconsulation",
            name="schedule",
            field=models.DateTimeField(),
        ),
    ]
