# Generated by Django 4.1.7 on 2023-05-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0024_alter_userdetails_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationfacilities",
            name="is_cancelled_by_admin",
            field=models.BooleanField(default=False),
        ),
    ]
