# Generated by Django 4.1.7 on 2023-05-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0025_reservationfacilities_is_cancelled_by_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="is_generated",
            field=models.BooleanField(default=False),
        ),
    ]
