# Generated by Django 4.1.7 on 2023-05-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0026_billing_is_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="transac_id",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="reference_number",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
    ]
