# Generated by Django 4.1.7 on 2023-05-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0027_billing_transac_id_alter_billing_reference_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationfacilities",
            name="is_bill_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservationfacilities",
            name="reference_number",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
    ]
