# Generated by Django 4.1.7 on 2023-05-14 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0028_reservationfacilities_is_bill_generated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 5, 14, 11, 28, 49, 928062, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
